### PR TITLE
Fix overflow of entity names and shrinking of icons in explorer

### LINKED ISSUE #799: Arrows in explorer shrink
https://codesandbox.io/s/nervous-haze-2yyz7?file=/src/index.tsx

### PR DESCRIPTION
**Pull request by axelboc**
Fix #799 

### Before

 image

### After

image

### CODE REVIEW

**Comment by axelboc** [comment]
Testing the approval flow now while I'm at it!

/approve

**Review by loichuder — APPROVED** [review]

**Pull request merged**
