### PR TITLE
Fix log axis showing too many ticks

### LINKED ISSUE #146: Too many ticks on index axis
Index axes currently show ticks at non-integer values when zoomed in or with small datasets. This is caused by the linear scale that is used, which is linked to the way VX `Axis` works.

Previously, we used to pass `numTicks` through `Math.min()` to get around the problem, but this is a bit hacky, since the numbers are a bit magic.

The current linear scale has another downside linked to #144: if we stop centering ticks on heatmaps, we'll end up with ticks on the right/top of the last "data pixels". What we want is more something like `scaleBand` or `scalePoint`, but with a linear input domain.

My recommendation would be to implement our own scale, which I think would be relatively easy to do.

### LINKED ISSUE #183: [Line] Too many ticks with log scale
image

### PR DESCRIPTION
**Pull request by axelboc**
Fix #183 

image

### CODE REVIEW

**Review by loichuder — CHANGES_REQUESTED** [review]
I am sorry to raise an issue while it seemed so elegantly handled: if you display only labels for exact powers of 10, it means you can have **only** ticks without labels when zooming (see below).

I would prefer that labels continue to appear in this case as in the linear case :slightly_smiling_face: 

image

**Comment by axelboc** [comment]
No worries at all, very good point. Perhaps I could take the minimum of the number of ticks requested and the number of ticks actually generated by D3?

**Comment by loichuder** [comment]
Actually, the axe of the colorbar has the behaviour you want to implement, without any tuning from us. 

Perhaps we are missing an `Axis` option that would also to have the same behaviour for the `AxisSystem` without any custom implementation ?

image

**Comment by axelboc** [comment]
Good call! 

```js
tickFormat={yTicksScale.tickFormat(adaptedNumTicks(height), '.3')}
```

**Comment by vasole** [comment]
You should not try to reinvent the wheel. Just take a look at how it is done in silx for the OpenGL backend

For reference, you can take a look at the Graphics Gems book chapter Nice Numbers for Graph Labels from Paul S. Heckbert.

**Comment by axelboc** [comment]
Still losing ticks at some zoom levels with `scale.tickFormat(...)`...

image

**Comment by axelboc** [comment]
Closing as the solution is not satisfactory. I've updated the issue to document the attempts: https://github.com/silx-kit/h5web/issues/183#issuecomment-696727626

**Pull request closed without merging**
