### PR TITLE
Add interactive demo to "Stacking" documentation page

### PR DESCRIPTION
**Pull request by axelboc**
Been wanting to do this for a while. It will make testing the stacking order much simpler. Of course, writing a visual diffing test for this is a bit tricky since it requires hovering/zooming/panning...

Peek 2023-10-10 13-17

### CODE REVIEW

**Comment by axelboc** [comment]
The visual diffing tests have become super flaky for some reason. There are a few pixels that change randomly on some dashed underlines in the dimension mapper. Very frustrating.

**Review by loichuder — APPROVED** [review]
Looks good !

**Pull request merged**
