### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by axelboc**
Last round of upgrades, just for the satisfaction of getting down to this minimal table of outdated dependencies:

image

- https://github.com/simonsmith/cypress-image-snapshot/releases/tag/8.1.2
- https://github.com/testing-library/user-event/releases/tag/v14.5.0
- https://docs.cypress.io/guides/references/changelog#13-2-0
- https://github.com/testing-library/cypress-testing-library/releases/tag/v10.0.0
- https://github.com/ai/nanoid/blob/main/CHANGELOG.md#50

### CODE REVIEW

**Review by axelboc — COMMENTED** [review]
Electron upgrade in Cypress, which explains the mostly invisible changes to the screenshots.

**Review by loichuder — APPROVED** [review]
Props for the complete deps upgrade :wink:

**Pull request merged**
