### PR TITLE
Choose best layout based on axis units

### LINKED ISSUE #1198: [Heatmap] Don't keep ratio when units don't match
### Is your feature request related to a problem?

See https://github.com/silx-kit/silx/issues/3626

> Working with 2d datasets in NeXus hdf5 with different units on the x- and y-axis I was wondering if there is a way to tell silx view to open a NXdata image view with the option "Do not keep data aspect ration" activated? By default it seems to keep the aspect ratio.

### Requested solution or feature

The `layout` config option currently always defaults to `cover` (i.e. keep ratio). Instead, it could default to `fill` (i.e. don't keep ratio) when the axes have different units.

### Alternatives you've considered

`SILX_style` could be extended with an `aspect` option -- see https://github.com/silx-kit/silx/issues/3626#issuecomment-1228566872.

### Additional context

We'll have to review the way we persist the `layout` configuration option, or whether it still needs to be persisted at all, as a dynamic default is incompatible with persistence across reloads.

### PR DESCRIPTION
**Pull request by axelboc**
Fix #1198 

In the mock `NXdata` group below, the axis units are different so the layout is now set to `fill` automatically when the group is selected (i.e. keep ratio disabled):

image

You can play around with the persistence behaviour by switching between a NeXus image and a heatmap visualization and toggling "keep ratio". It works as per `scaleType` and #1199.

There are more test cases in the file provided by @t20100: http://127.0.0.1:5173/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Ftest_units.h5. I did not bring any of them into our mock metadata, since we already have cases with no units as well as different units for the two axes, which is enough to test both conditional branches.

Also, I did not bother dealing with the `NxRGB` visualization since we don't pass axis values/labels to the mapped vis anyway.

### CODE REVIEW

**Review by loichuder — COMMENTED** [review]
In my opinion, if one of the units is not defined, it means we cannot make an educated suggestion on the layout.

 I propose then the following behaviour
- One unit or more undefined: no suggestion (suggest `undefined`)
- Both units defined and **equal**: suggest `cover`
- Both units defined and **different**: suggest `fill`

**Comment by t20100** [comment]
In silx we did it this way:

> Keep aspect ratio by default and disable it when axes have different @units (i.e., keep aspect ratio for axes with the same @units or without @units - if an axis as @units and the other not, it's different @units) https://github.com/silx-kit/silx/issues/3626#issuecomment-1236928823

https://github.com/silx-kit/silx/pull/3660

From what @loichuder propose, I would only make a change for the case of "one unit defined and the other not defined" and consider it as **different** units.
A case for this is a 2D dataset composed of many 1D dataset: rows are indices (unitless) and columns are the coordinates of the data.
And if there is no `@unit` at all, you keep using the current user choice.

**Comment by axelboc** [comment]
Alright, thanks for your inputs. So in the end I'm just changing the case where neither units are defined to no longer enforce the `cover` layout. Now, it just defaults to the user's preference. I've abstracted this logic into a utility function with unit tests.

**Review by loichuder — APPROVED** [review]
Great example of refactorings done well: the final PR is quite short :clap:

**Pull request merged**
